# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/databases-1.json
Databases:
  pattern-demos-lock:
    Url: jdbc:hsqldb:mem:pattern_demos_lock
    Driver: org.hsqldb.jdbc.JDBCDriver
    Password: ${decrypt:}
