# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  patterns-demo-lock:
    Url: jdbc:hsqldb:mem:pattern_demos_lock
    Driver: org.hsqldb.jdbc.JDBCDriver
    UserName: sa
    Password: ${decrypt:wPU92HMFH8zknRu0JgyQ9Q==}
