# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  com:
    axonivy:
      demo:
        patterndemos:
          admintask:
            # Change value to false to avoid error and admin task in the demo.
            forceError: true
